const CartActionTypes = {
    TOGGLE_CART_HIDDEN: 'TOGGLE_CART_HIDDEN',
    ADD_ITEM: 'ADD_ITEM',
    CLEARE_ITEM_FROM_CART: 'CLEARE_ITEM_FROM_CART',
    REMOVE_ITEM: 'REMOVE_ITEM', 
    CLEAR_CART: 'CLEAR_CART'
};

export default CartActionTypes;