# Generated by Django 4.0 on 2022-01-21 13:02

import colorfield.fields
import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('country', models.CharField(max_length=60, verbose_name='Country')),
                ('region', models.CharField(max_length=100, null=True, verbose_name='Region')),
                ('town', models.CharField(max_length=100, verbose_name='Town')),
                ('street', models.CharField(max_length=100, verbose_name='Street')),
                ('house', models.CharField(max_length=10, verbose_name='House')),
                ('flat', models.PositiveIntegerField(null=True, verbose_name='Flat')),
            ],
            options={
                'verbose_name': 'Address',
                'verbose_name_plural': 'Addresses',
                'unique_together': {('country', 'region', 'town', 'street', 'house', 'flat')},
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Category Name')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='categories/', verbose_name='Category Image')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('birthdate', models.DateField(verbose_name='Birth Date')),
                ('image', models.ImageField(null=True, upload_to='customers/', verbose_name='User Image')),
                ('phone', models.CharField(max_length=13, verbose_name='Phone Number')),
                ('store_owner', models.BooleanField(default=False, verbose_name='Shop Owner')),
                ('date_joined', models.DateField(default=datetime.datetime(2022, 1, 21, 13, 2, 27, 633051, tzinfo=utc), verbose_name='Date Joined')),
                ('address', models.ManyToManyField(null=True, related_name='customer_addresses', to='api.Address', verbose_name='Address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Product Name')),
                ('description', models.TextField(verbose_name='Product Description')),
                ('price', models.PositiveIntegerField(default=0, verbose_name='Price')),
                ('total_count', models.PositiveIntegerField(default=1, verbose_name='Number of products')),
                ('created_at', models.DateField(default=datetime.datetime(2022, 1, 21, 13, 2, 27, 635176, tzinfo=utc), verbose_name='Created Date')),
                ('size', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=5), default='M', size=None)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Shop Name')),
                ('image', models.ImageField(upload_to='shops/', verbose_name='Shop Image')),
                ('info', models.TextField(verbose_name='Shop Info')),
                ('created_date', models.DateField(verbose_name='Created Date')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer', verbose_name='Shop Owner')),
            ],
            options={
                'verbose_name': 'Shop',
                'verbose_name_plural': 'Shops',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(default='product_one.png', upload_to='products/%Y/%m/%d/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='api.product')),
            ],
            options={
                'verbose_name': 'Product image',
                'verbose_name_plural': 'Product images',
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', max_length=18, samples=[('#FFFFFF', 'white'), ('#000000', 'black'), ('#06bf06', 'green'), ('#0625bf', 'blue'), ('#ed0909', 'red')])),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.product', verbose_name='Related product')),
            ],
            options={
                'verbose_name': 'Product Color',
                'verbose_name_plural': 'Product Colors',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.shop', verbose_name='Related Shop'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=13, verbose_name='Phone Number')),
                ('created_at', models.DateField(default=datetime.datetime(2022, 1, 21, 13, 2, 27, 636589, tzinfo=utc), verbose_name='Created Date')),
                ('comment', models.TextField(verbose_name='Order comment')),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.address')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.customer')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
