# Generated by Django 4.0 on 2022-01-29 15:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_customer_date_joined_alter_order_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2022, 1, 29, 15, 34, 36, 46974, tzinfo=utc), verbose_name='Date Joined'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 1, 29, 15, 34, 36, 50557, tzinfo=utc), verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2022, 1, 29, 15, 34, 36, 49225, tzinfo=utc), verbose_name='Created Date'),
        ),
    ]
