# Generated by Django 4.0 on 2021-12-17 01:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='date_joined',
            field=models.DateField(default=datetime.datetime(2021, 12, 17, 1, 17, 41, 965812, tzinfo=utc), verbose_name='Date Joined'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(null=True, upload_to='', verbose_name='User Image'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 12, 17, 1, 17, 41, 969882, tzinfo=utc), verbose_name='Created Date'),
        ),
        migrations.AlterField(
            model_name='product',
            name='created_at',
            field=models.DateField(default=datetime.datetime(2021, 12, 17, 1, 17, 41, 968289, tzinfo=utc), verbose_name='Created Date'),
        ),
    ]
